name: betterCode
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas=2.3.2
  - r-base=4.5
  - r-dplyr
  - r-lubridate
  - r-tidyr
  - r-tibble
  - r-data.table
  - r-viridis
  - r-optparse
